### ISSUE TITLE
[Feature request] BME280 support

### ISSUE THREAD

**Issue by Potracheno** [s60sc/ESP32-IO_Extender#1]
Is it possible to add BME280 support ? If I understood right we have enough pins and memory for it. I don't ask you to do it but can you describe briefly what should I do to implement this support ?

**Comment by s60sc** [comment]
You need to add a handler to peripherals.cpp and add configurable info to configs.txt,  appGlobals.h, appSpecific.cpp.
Use DS18B20 handler as an example
